[package]
name = "learning-win32"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = "1.0.63"
windows = { version = "0.58", features = [
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
] }
